export const APP_SETINITLOADED = 'APP_SETINITLOADED';

export const MOVIE_SETMOVIES = 'MOVIE_SETMOVIES';
export const MOVIE_SETMYLIST = 'MOVIE_SETMYLIST';
export const MOVIE_SETCATEGORIES = 'MOVIE_SETCATEGORIES';
export const MOVIE_SETDETAIL = 'MOVIE_SETDETAIL';